name: tap_canvas_example
description: An example project to demo tap_canvas
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: "^1.0.2"
  flutter:
    sdk: flutter
  tap_canvas:
    path: ../

flutter:
  uses-material-design: true
