---
name: Coverage Report

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2.3.4
      - name: Set up Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Ensure code coverage checks correct files
        run: |
          #!/bin/bash
          chmod +x bin/prep_files_for_code_coverage_check.sh
          sudo ./bin/prep_files_for_code_coverage_check.sh tap_canvas
      - name: Run the tests (with coverage)
        run: flutter test --coverage
      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v1.2.2
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
